### ISSUE TITLE
Importing Glams

### ISSUE THREAD

**Issue by alolune** [caitlyn-gg/Glamaholic#1]
Hi, for the past 2-3 days I am unable to copy glams from URLs and import them into glamaholic like normal. I copy URL, go to plates drop down, and select import from clipboard but nothing happens. I have tried different URLs. I'm not sure if glamaholic has a limit to how many saved, but I deleted some and tried again and still unable to import. Have restarted game a few times. Please let me know if you need any more info.

**Comment by caitlyn-gg** [comment]
> Hi, for the past 2-3 days I am unable to copy glams from URLs and import them into glamaholic like normal. I copy URL, go to plates drop down, and select import from clipboard but nothing happens. I have tried different URLs. I'm not sure if glamaholic has a limit to how many saved, but I deleted some and tried again and still unable to import. Have restarted game a few times. Please let me know if you need any more info.

Assuming you are importing from Eorzea Collection, you need to make sure that you're using the Eorzea Collection menu to import and _not_ the Plate menu. The Plate -> Import from Clipboard option is for JSON imports from other Glamaholic users.

**Comment by alolune** [comment]
Thank you! My fault
